### ISSUE TITLE
Setting background color leaves artifact

### ISSUE THREAD

**Issue by Eckelf** [quassum/SwiftUI-Tooltip#16]
**Describe the bug**
Setting the background color leaves an artifact when selecting a side that is not `top`.

**To Reproduce**
1. Configure side `trailing` (also tested with `leading` & `bottom`, same issue)
2. Set `backgroundColor` to something not `clear`

**Expected behavior**
All of the tooltip's background is set to `backgroundColor`.

**Screenshots**
<img width="204" alt="artifact-trailing" src="https://user-images.githubusercontent.com/4563901/147857721-450d4f5e-6938-42af-9164-74ec3e338c64.png">

**Desktop (please complete the following information):**
 - OS: iOS 15.2
 - Version 1.1.2

**Comment by Eckelf** [comment]
I think the offsets are wrong at https://github.com/quassum/SwiftUI-Tooltip/blob/main/Sources/SwiftUITooltip/TooltipModifier.swift#L167

**Comment by bring-shrubbery** [comment]
Uff, yeah. I'll try to fix it this week. Or feel free to send a PR ;)

**Comment by b95505017** [comment]
@bring-shrubbery Any update since that week?

**Comment by bring-shrubbery** [comment]
@b95505017 Nope, literally didn't have a single free hour since then. Will try to take a look at it this weekend though :)

**Comment by bring-shrubbery** [comment]
Hey @Eckelf, @b95505017! I fixed this issue. The solution is not perfect - you can still see one transparent pixel where the arrow connects, but it's the best I could do with the time that I have. I encourage you to send a pull request to make it better - just need to add a small rectangle and position it correctly, so that the arrow looks nice on all the `side:` parameter settings.
